name: Action


on:
  
  schedule:
   - cron: "0 17 * * *"
  

env:
  TZ: Asia/Shanghai

jobs:
  # a
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requestment
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests beautifulsoup4 lxml argparse
      - name: Run
        env:         
         TOKEN: ${{ secrets.TOKEN }}         
         
        run: TOKEN=$TOKEN python3 ./run.py

      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41398134+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed origin/main
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
